
# Project configuration
name = "jsonbin"
main = "dist/_worker.js"           # Your entry point file
compatibility_date = "2025-10-08"


[[kv_namespaces]]
binding = "JSONBIN"
id = "930a89c69cf24e3ab807b6d0a5d45035"         # Production ID (required for wrangler to recognize the block)
preview_id = "jsonbin_pre" # Recommended: Keeps local dev data separate


[assets]
directory = "./dist"   # Folder containing your static files
binding = "ASSETS"     # This enables env.ASSETS.fetch()